#Candle Batcher (minutes)
[CANDLE]
size = 15

# SMA Trends
[SMA]
long = 1000
short = 50

# BULL
[BULL]
rsi = 10
mod_high = 5
mod_low = -5
high = 80
low = 60

# BEAR
[BEAR]
rsi = 15
high = 50
low = 20
mod_high = 15
mod_low = -5

# ADX
[ADX]
adx = 3
high = 70
low = 50